apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: th4s8ryix-java-quarkus
  janus-idp.io/tekton: th4s8ryix-java-quarkus
  backstage.io/kubernetes-id: th4s8ryix-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: th4s8ryix-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
